---
abstract: 'Dancer Plugin for Interchange6 Open Source Shop Machine'
author:
  - 'Stefan Hornburg (Racke) <racke@linuxia.de>'
build_requires:
  DBICx::TestDatabase: '0'
  Test::Database: '0'
  Test::Most: '0'
  Test::Roo: '1.004'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.98, CPAN::Meta::Converter version 2.142690'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Dancer-Plugin-Interchange6
no_index:
  directory:
    - t
    - inc
requires:
  Business::OnlinePayment: '3.02'
  Dancer: '1.3098'
  Dancer::Plugin::Auth::Extensible: '0'
  Dancer::Plugin::Auth::Extensible::Provider::DBIC: '0'
  Dancer::Plugin::DBIC: '0'
  Dancer::Session::DBIC: '0'
  Interchange6: '0.061'
  Interchange6::Schema: '0.070'
  YAML: '0'
  perl: '5.014000'
resources:
  IRC: irc://irc.freenode.net/#interchange
  bugtracker: https://github.com/interchange/Dancer-Plugin-Interchange6/issues
  repository: https://github.com/interchange/Dancer-Plugin-Interchange6.git
version: '0.071'
