---
abstract: 'Dancer Plugin for Interchange6 Open Source Shop Machine'
author:
  - 'Stefan Hornburg (Racke) <racke@linuxia.de>'
build_requires:
  DBICx::TestDatabase: 0
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.76, CPAN::Meta::Converter version 2.132510'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Dancer-Plugin-Interchange6
no_index:
  directory:
    - t
    - inc
requires:
  Business::OnlinePayment: 3.02
  Dancer: 1.3098
  Dancer::Plugin::DBIC: 0
  Interchange6: 0.001
  Interchange6::Schema: 0.004
  YAML: 0
resources:
  bugtracker: https://github.com/interchange/Dancer-Plugin-Interchange6/issues
  repository: https://github.com/interchange/Dancer-Plugin-Interchange6.git
version: 0.001
